project:
  type: website

website:
  title: "Site de Test Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Acceuil
      - about.qmd
      - sephora_scrape.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: true 
  cache: true
